config/routes.rb
Rails.application.routes.draw do
  resources :proverbes
  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proverbe.rb
class Proverbe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/proverbes_controller.rb
class ProverbesController < ApplicationController
  before_action :set_proverbe, only: [:show, :edit, :update, :destroy]

  # GET /proverbes
  # GET /proverbes.json
  def index
    @proverbes = Proverbe.all
  end

  # GET /proverbes/1
  # GET /proverbes/1.json
  def show
  end

  # GET /proverbes/new
  def new
    @proverbe = Proverbe.new
  end

  # GET /proverbes/1/edit
  def edit
  end

  # POST /proverbes
  # POST /proverbes.json
  def create
    @proverbe = Proverbe.new(proverbe_params)

    respond_to do |format|
      if @proverbe.save
        format.html { redirect_to @proverbe, notice: 'Proverbe was successfully created.' }
        format.json { render :show, status: :created, location: @proverbe }
      else
        format.html { render :new }
        format.json { render json: @proverbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proverbes/1
  # PATCH/PUT /proverbes/1.json
  def update
    respond_to do |format|
      if @proverbe.update(proverbe_params)
        format.html { redirect_to @proverbe, notice: 'Proverbe was successfully updated.' }
        format.json { render :show, status: :ok, location: @proverbe }
      else
        format.html { render :edit }
        format.json { render json: @proverbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proverbes/1
  # DELETE /proverbes/1.json
  def destroy
    @proverbe.destroy
    respond_to do |format|
      format.html { redirect_to proverbes_url, notice: 'Proverbe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proverbe
      @proverbe = Proverbe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proverbe_params
      params.require(:proverbe).permit(:citation, :auteur)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proverbes_helper.rb
module ProverbesHelper
end

app/views/home/index.html.erb
<%= content_for :nav do %>
<%= render "partials/navbar" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hosto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../vendore/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  </head>

  <body>

<div id="wrapper">
  <%= yield :nav %>

          <%= yield %>

</div>
<%= yield :tab %>
      <!-- jQuery -->
      <script src="../vendor/jquery/jquery.min.js"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>

      <!-- Metis Menu Plugin JavaScript -->
      <script src="../vendor/metisMenu/metisMenu.min.js"></script>
      <!-- DataTables JavaScript -->
          <script src="../vendore/datatables/js/jquery.dataTables.min.js"></script>
          <script src="../vendore/datatables-plugins/dataTables.bootstrap.min.js"></script>
          <script src="../vendore/datatables-responsive/dataTables.responsive.js"></script>

          <!-- Custom Theme JavaScript -->
          <script src="../dist/js/sb-admin-2.js"></script>

          <!-- Page-Level Demo Scripts - Tables - Use for reference -->
          <script>
          $(document).ready(function() {
              $('#dataTables-example').DataTable({
                  responsive: true
              });
          });
          </script>

      <script type="text/javascript">
        $(function(){
          /* ========================================================================= */
          /*	Contact Form
          /* ========================================================================= */

          //autoclose
          $(".alert-message").alert();
          window.setTimeout(function() { $(".alert-message").alert('close'); }, 2000);

          $('#myModal').on('shown.bs.modal', function () {
              $('#myInput').focus()
            })

          });
      </script>


    


  </body>
</html>

app/views/partials/_tabelung.html.erb
<style media="screen">
#myInput {
  background-image: url('/css/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}

#myTable {
  border-collapse: collapse; /* Collapse borders */
  width: 100%; /* Full-width */
  border: 1px solid #ddd; /* Add a grey border */
  font-size: 18px; /* Increase font-size */
}

#myTable th, #myTable td {
  text-align: left; /* Left-align text */
  padding: 12px; /* Add padding */
}

#myTable tr {
  /* Add a bottom border to all table rows */
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  /* Add a grey background color to the table header and on hover */
  background-color: #f1f1f1;
}
</style>



<script type="text/javascript">
function myFunction() {
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

app/views/proverbes/_form.html.erb
<%= simple_form_for(@proverbe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :citation %>
    <%= f.input :auteur %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/proverbes/edit.html.erb
<h1>Editing Proverbe</h1>

<%= render 'form', proverbe: @proverbe %>

<%= link_to 'Show', @proverbe %> |
<%= link_to 'Back', proverbes_path %>

app/views/proverbes/index.html.erb
<%= content_for :nav do %>
<%= render "partials/navbar" %>
<% end %>


<div id="page-wrapper">
      <div class="row">
          <div class="col-lg-12">
              <h1 class="page-header">Proverbes</h1>
            </div>
            <!-- /.col-lg-12 -->
      </div>

              <!--<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Tapez le nom de l'auteur.."> -->
              <!-- /.row -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Mes Proverbes
                            </div>
                            <div class="panel-body">
                                  <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                          <tr class="header">
                                            <th>Citation</th>
                                            <th>Auteur</th>
                                            <th></th>
                                            <th></th>
                                            <th></th>
                                            <!--<th colspan="3"></th>-->
                                          </tr>
                                        </thead>

                                        <tbody>
                                          <% @proverbes.each do |proverbe| %>
                                            <tr>
                                              <td><%= proverbe.citation %></td>
                                              <td><%= proverbe.auteur %></td>
                                              <td><%= link_to 'Show', proverbe %></td>
                                              <td><%= link_to 'Edit', edit_proverbe_path(proverbe) %></td>
                                              <td><%= link_to 'Destroy', proverbe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                            </tr>
                                          <% end %>
                                        </tbody>
                                      </table>

              <br>

              <%= link_to 'New Proverbe', new_proverbe_path %>
                                      </div>
                                  <!-- /.panel-body -->
                              </div>
                              <!-- /.panel -->
                          </div>
                          <!-- /.col-lg-12 -->
                      </div>
                      <!-- /.row -->

    <!--<%= content_for :tab do %>
    <%= render "partials/tabelung" %>
    <% end %>-->

app/views/proverbes/new.html.erb
<h1>New Proverbe</h1>

<%= render 'form', proverbe: @proverbe %>

<%= link_to 'Back', proverbes_path %>

app/views/proverbes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Citation:</strong>
  <%= @proverbe.citation %>
</p>

<p>
  <strong>Auteur:</strong>
  <%= @proverbe.auteur %>
</p>

<%= link_to 'Edit', edit_proverbe_path(@proverbe) %> |
<%= link_to 'Back', proverbes_path %>